# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["ASPRIN_DATABASE_USERNAME"] %>
  password: <%= ENV["ASPRIN_DATABASE_PASSWORD"] %>
  host: <%= ENV["ASPRIN_DATABASE_HOST"] || "localhost" %>
  port: <%= ENV["ASPRIN_DATABASE_PORT"] || 5432 %>

development:
  <<: *default
  database: asprin_development

test:
  <<: *default
  database: asprin_test

production:
  <<: *default
  database: asprin_production
  username: <%= ENV["ASPRIN_DATABASE_USERNAME"] %>
  password: <%= ENV["ASPRIN_DATABASE_PASSWORD"] %>
